### ISSUE TITLE
Amazing! I like to have more ways to interact, for example, SQL queries

### ISSUE THREAD

**Issue by wosledon** [otis11/SmileDB#2]
Thanks for your support! The rest of the plugins are too old-fashioned!

**Comment by otis11** [comment]
Hi there!
You should be able to select `Query` inside the table view where the database filter is selected per default. (the query field doesn't support any highlighting yet, its just a plain text field as this extension is in a very early stage). Thanks for your feedback! 

![smiledb~3.png](https://github.com/eat4/SmileDB/assets/148579276/596aaa68-48d2-4aaa-9178-d0bce0444c0f)
