### ISSUE TITLE
The screen always reloads automatically

### ISSUE THREAD

**Issue by hclever** [otis11/SmileDB#20]
- VS Code Version: 1.91.1
- SmileDB Version: 0.2.5

Bug: The screen always reloads automatically. The parameters I entered are deleted

https://github.com/user-attachments/assets/93c05e0b-f253-4063-b8f0-4ac719a769fc

**Comment by otis11** [comment]
Thanks for pointing that out. Just released version `0.2.6`, which contains the context for tables and edit-connection webviews per default (can also be turned off if needed). VSCode could need a restart for the default configuration to apply.
