### ISSUE TITLE
There seems to be some problems with Redis's handling of value.

### ISSUE THREAD

**Issue by wosledon** [otis11/SmileDB#3]
There seems to be some problems with Redis's handling of value.
My value Types: key-value, hash, redis-mq

![image](https://github.com/eat4/SmileDB/assets/49866401/dc1d9128-ea6b-45b3-9c2d-025fbd37a1cc)

**Comment by otis11** [comment]
The redis implementation right now only uses `get` to retrieve keys. It should use different methods for different keys (for example `hget` for hash keys. https://stackoverflow.com/a/44444966

Need to implement a way to get the type for redis value to use the correct method on it.

Redis Connector: https://github.com/eat4/SmileDB/blob/main/src/modules/redis/RedisPoolConnection.ts

Unfortunately i am only able to work on this in about 1 month from now, as i am busy right now :/.

**Comment by wosledon** [comment]
It's okay, I'm looking forward to seeing it grow.

**Comment by otis11** [comment]
Version `0.1.2` is release which improves querying and interacting with the different data types in Redis and should now support all data types. If there is still an issue please open a new issue. Thanks and Happy new Year! :)

**Comment by wosledon** [comment]
> Version is release which improves querying and interacting with the different data types in Redis and should now support all data types. If there is still an issue please open a new issue. Thanks and Happy new Year! :)`0.1.2`

Thanks for your support!  Happy New Year! :)
