### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by khtodod** [otis11/SmileDB#4]
Thanks for creating such a cool and nice extension with Visual Studio Code. However, I've come across a bug in the dark theme, and I've attached an image to highlight the issue.

![Screenshot 2024-01-08 at 16 04 26](https://github.com/eat4/SmileDB/assets/26436700/ad239e58-2a29-4466-bfeb-ef9ce7b519c2)

**Comment by otis11** [comment]
Happy to help! Could you clarify which theme you are using? 
The colors used are adopted from the VSCode color scheme your editor is using. I think there needs to be some changes which color variables get used by the extension.

**Comment by khtodod** [comment]
Theme: Gruvbox DrakeLords

**Comment by otis11** [comment]
Version `0.1.4` is published, which improves the theme colors used by the extension. If there is still something off, please open a new issue. Thanks :)
